title: DIY done the right way
author: GitHub DT4YL8R
email: dtay10r@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Here at diy daves we pride ourselves on customer satisfaction, we offer our expertise to you on flexible time slots and low prices.
  all our work is garaunteed for 6 months.

# social links
twitter_username: tayl8r39
github_username:  DT4YL8R

show_excerpts: true # set to false to remove excerpts on the homepage
